theme: minima
title: The Dog Blong
author: kennedyjblanchard
email: kennedyjblanchard@gmail.com
description: > # this means to ignore newlines until "baseurl:"
a blog about dogs, the place where readers can come, read stories
and share stories all about dogs and their experience with these creatures.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  kennedyjblanchard # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
